# Generated by Django 4.0.4 on 2022-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=10)),
                ('user_mname', models.CharField(max_length=10)),
                ('user_lname', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=20)),
                ('user_phone', models.IntegerField(max_length=10)),
                ('user_pass', models.CharField(max_length=10)),
                ('user_isPO', models.BooleanField()),
                ('user_Pname', models.CharField(max_length=20)),
                ('user_Paddr', models.CharField(max_length=50)),
            ],
        ),
    ]
