# Generated by Django 4.0.4 on 2022-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_users_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_Pimage',
            field=models.ImageField(default=None, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_Paddr',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_Pname',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
