# Generated by Django 4.0.4 on 2022-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users_user_pimage_alter_users_user_paddr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_Paddr',
            field=models.TextField(),
        ),
    ]
