# Generated by Django 4.0.4 on 2022-06-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_user_paddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_PAname',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_Pname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
