# Generated by Django 4.0.4 on 2022-06-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_users_user_paname_alter_users_user_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_Paddr',
            field=models.TextField(default=''),
        ),
    ]
