# Generated by Django 4.0.4 on 2022-07-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_users_user_paddr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_Pimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='home/images/%y'),
        ),
    ]
