# Generated by Django 4.0.4 on 2022-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_users_username_alter_users_user_paname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_isPO',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_pass',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_Pimage',
            field=models.ImageField(blank=True, default='home/images/row1.jpg', null=True, upload_to='home/images/'),
        ),
    ]
