# Generated by Django 4.0.5 on 2022-07-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_users_user_ispo_remove_users_user_pass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_Username', models.CharField(default='', max_length=50)),
                ('U_Username', models.CharField(default='', max_length=50)),
                ('U_FirstName', models.CharField(max_length=50)),
                ('U_LastName', models.CharField(max_length=50)),
                ('U_MobNo', models.IntegerField()),
                ('U_Email', models.CharField(max_length=50)),
                ('U_VehicleNo', models.CharField(max_length=50)),
                ('U_TimeSlot', models.TimeField()),
                ('U_Duration', models.CharField(max_length=10)),
            ],
        ),
    ]
