# Generated by Django 4.0.5 on 2022-07-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='U_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='U_token',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
    ]
