# Generated by Django 4.0.5 on 2022-07-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking_u_status_booking_u_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='U_Duration',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='U_TimeSlot',
            field=models.TimeField(default='00:00'),
        ),
    ]
