# Generated by Django 4.0.5 on 2022-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_booking_u_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='U_VType',
            field=models.CharField(default='', max_length=4),
        ),
    ]
