# Generated by Django 4.0.5 on 2022-07-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_booking_u_vtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extended',
            field=models.BooleanField(default=False),
        ),
    ]
