# Generated by Django 4.0.4 on 2022-07-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_check_o_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
