# Generated by Django 4.0.4 on 2022-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_slots',
            field=models.IntegerField(default=0),
        ),
    ]
