# Generated by Django 4.0.4 on 2022-07-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_users_user_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_slots',
        ),
    ]
